# Generated by Django 3.0 on 2022-04-07 09:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_second'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 7, 9, 33, 48, 922095, tzinfo=utc)),
        ),
    ]
